import = [
	"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"	
]

[window]
dynamic_padding = true
padding = {x = 5, y = 2}
opacity = 0.85

[font]
normal = {family = "CodeNewRoman Nerd Font Mono", style = "Regular"}
bold = {family = "CodeNewRoman Nerd Font Mono", style = "Bold"}
italic = {family = "CodeNewRoman Nerd Font Mono", style = "Italic"}
size = 16

